#define PJ_CONFIG_IPHONE 1
#ifdef PJMEDIA_AUDIO_DEV_HAS_OPENSL
#undef PJMEDIA_AUDIO_DEV_HAS_OPENSL
#endif
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL 0
#define PJSIP_AUTH_AUTO_SEND_NEXT 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_SRTP_HAS_DTLS 1
#define PJMEDIA_HAS_OPUS_CODEC 1
#define PJ_AUTOCONF 1
#define PJMEDIA_HAS_SRTP 1
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL_ES 1
#define PJMEDIA_VIDEO_DEV_HAS_IOS_OPENGL 1
#include <OpenGLES/ES3/glext.h>
#include <VialerPJSIP/pj/config_site_sample.h>
